# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ServerUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(448, 485)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(448, 485))
        MainWindow.setMaximumSize(QtCore.QSize(448, 485))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 421, 241))
        self.tabWidget.setObjectName("tabWidget")
        self.acamTab = QtWidgets.QWidget()
        self.acamTab.setAccessibleName("")
        self.acamTab.setAutoFillBackground(False)
        self.acamTab.setObjectName("acamTab")
        self.addc_Button = QtWidgets.QPushButton(self.acamTab)
        self.addc_Button.setGeometry(QtCore.QRect(200, 130, 201, 31))
        self.addc_Button.setObjectName("addc_Button")
        self.label_5 = QtWidgets.QLabel(self.acamTab)
        self.label_5.setGeometry(QtCore.QRect(40, 19, 61, 21))
        self.label_5.setObjectName("label_5")
        self.SE_lineEdit = QtWidgets.QLineEdit(self.acamTab)
        self.SE_lineEdit.setGeometry(QtCore.QRect(100, 50, 271, 20))
        self.SE_lineEdit.setObjectName("SE_lineEdit")
        self.label_8 = QtWidgets.QLabel(self.acamTab)
        self.label_8.setGeometry(QtCore.QRect(20, 49, 71, 21))
        self.label_8.setObjectName("label_8")
        self.CIP_lineEdit = QtWidgets.QLineEdit(self.acamTab)
        self.CIP_lineEdit.setGeometry(QtCore.QRect(100, 20, 271, 20))
        self.CIP_lineEdit.setObjectName("CIP_lineEdit")
        self.CamNameComboBox_3 = QtWidgets.QComboBox(self.acamTab)
        self.CamNameComboBox_3.setGeometry(QtCore.QRect(100, 80, 231, 21))
        self.CamNameComboBox_3.setObjectName("CamNameComboBox_3")
        self.CamNameComboBox_3.addItem("")
        self.CamNameComboBox_3.addItem("")
        self.CamNameComboBox_3.addItem("")
        self.CamNameComboBox_3.addItem("")
        self.label_17 = QtWidgets.QLabel(self.acamTab)
        self.label_17.setGeometry(QtCore.QRect(20, 80, 81, 21))
        self.label_17.setObjectName("label_17")
        self.tabWidget.addTab(self.acamTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.StrSenButton = QtWidgets.QPushButton(self.tab)
        self.StrSenButton.setGeometry(QtCore.QRect(30, 70, 101, 31))
        self.StrSenButton.setObjectName("StrSenButton")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 71, 21))
        self.label_3.setObjectName("label_3")
        self.CamNameComboBox = QtWidgets.QComboBox(self.tab)
        self.CamNameComboBox.setGeometry(QtCore.QRect(120, 30, 231, 21))
        self.CamNameComboBox.setObjectName("CamNameComboBox")
        self.StpSenButton = QtWidgets.QPushButton(self.tab)
        self.StpSenButton.setGeometry(QtCore.QRect(150, 70, 101, 31))
        self.StpSenButton.setObjectName("StpSenButton")
        self.delete_cam_Button = QtWidgets.QPushButton(self.tab)
        self.delete_cam_Button.setGeometry(QtCore.QRect(270, 70, 101, 31))
        self.delete_cam_Button.setObjectName("delete_cam_Button")
        self.delete_store_cam_Button = QtWidgets.QPushButton(self.tab)
        self.delete_store_cam_Button.setGeometry(QtCore.QRect(270, 180, 101, 31))
        self.delete_store_cam_Button.setObjectName("delete_store_cam_Button")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 71, 21))
        self.label_4.setObjectName("label_4")
        self.CamNameComboBox_2 = QtWidgets.QComboBox(self.tab)
        self.CamNameComboBox_2.setGeometry(QtCore.QRect(120, 150, 231, 21))
        self.CamNameComboBox_2.setObjectName("CamNameComboBox_2")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(100, 120, 281, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setEnabled(False)
        self.label_6.setGeometry(QtCore.QRect(10, 120, 81, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setEnabled(False)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.label_7.setObjectName("label_7")
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(90, 10, 291, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.usr_Password_lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.usr_Password_lineEdit.setGeometry(QtCore.QRect(90, 60, 271, 20))
        self.usr_Password_lineEdit.setObjectName("usr_Password_lineEdit")
        self.usr_Username_lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.usr_Username_lineEdit.setGeometry(QtCore.QRect(90, 30, 271, 20))
        self.usr_Username_lineEdit.setObjectName("usr_Username_lineEdit")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(30, 29, 51, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(30, 59, 51, 21))
        self.label_14.setObjectName("label_14")
        self.add_user_Button = QtWidgets.QPushButton(self.tab_2)
        self.add_user_Button.setGeometry(QtCore.QRect(270, 140, 111, 31))
        self.add_user_Button.setObjectName("add_user_Button")
        self.lvl_usr_ComboBox = QtWidgets.QComboBox(self.tab_2)
        self.lvl_usr_ComboBox.setGeometry(QtCore.QRect(130, 100, 231, 21))
        self.lvl_usr_ComboBox.setObjectName("lvl_usr_ComboBox")
        self.lvl_usr_ComboBox.addItem("")
        self.lvl_usr_ComboBox.addItem("")
        self.lvl_usr_ComboBox.addItem("")
        self.lvl_usr_ComboBox.addItem("")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(30, 100, 71, 21))
        self.label_18.setObjectName("label_18")
        self.tabWidget.addTab(self.tab_2, "")
        self.LogtextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.LogtextBrowser.setGeometry(QtCore.QRect(10, 270, 421, 161))
        self.LogtextBrowser.setObjectName("LogtextBrowser")
        self.logLabel = QtWidgets.QLabel(self.centralwidget)
        self.logLabel.setGeometry(QtCore.QRect(20, 250, 51, 21))
        self.logLabel.setObjectName("logLabel")
        self.LogtextBrowser.raise_()
        self.logLabel.raise_()
        self.tabWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 448, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.acamTab.setToolTip(_translate("MainWindow", "<html><head/><body><p>Add Camera</p></body></html>"))
        self.addc_Button.setText(_translate("MainWindow", "Add camera"))
        self.label_5.setText(_translate("MainWindow", "Camera IP:"))
        self.SE_lineEdit.setText(_translate("MainWindow", "c1"))
        self.label_8.setText(_translate("MainWindow", "Camera Name:"))
        self.CIP_lineEdit.setText(_translate("MainWindow", "0"))
        self.CamNameComboBox_3.setItemText(0, _translate("MainWindow", "1"))
        self.CamNameComboBox_3.setItemText(1, _translate("MainWindow", "2"))
        self.CamNameComboBox_3.setItemText(2, _translate("MainWindow", "3"))
        self.CamNameComboBox_3.setItemText(3, _translate("MainWindow", "4"))
        self.label_17.setText(_translate("MainWindow", "Level of Access"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.acamTab), _translate("MainWindow", "Add Control"))
        self.StrSenButton.setStatusTip(_translate("MainWindow", "it will activate the camera to send data to clients and store it for future access."))
        self.StrSenButton.setText(_translate("MainWindow", "Activate camera"))
        self.label_3.setText(_translate("MainWindow", "Camera Name"))
        self.StpSenButton.setStatusTip(_translate("MainWindow", "it will deactivate the camera but still exist and could be activated again."))
        self.StpSenButton.setText(_translate("MainWindow", "Deactivate camera"))
        self.delete_cam_Button.setStatusTip(_translate("MainWindow", "it will deactivate and remove the camera completely. but stored data still exist."))
        self.delete_cam_Button.setText(_translate("MainWindow", "delete camera"))
        self.delete_store_cam_Button.setStatusTip(_translate("MainWindow", "it will remove the data stored inside the server."))
        self.delete_store_cam_Button.setText(_translate("MainWindow", "delete stored data"))
        self.label_4.setText(_translate("MainWindow", "Camera Name"))
        self.label_6.setText(_translate("MainWindow", "Storage control"))
        self.label_7.setText(_translate("MainWindow", "Process control"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Camera Controller"))
        self.usr_Password_lineEdit.setText(_translate("MainWindow", "1234"))
        self.usr_Username_lineEdit.setText(_translate("MainWindow", "new_guest"))
        self.label_13.setText(_translate("MainWindow", "Username"))
        self.label_14.setText(_translate("MainWindow", "Password"))
        self.add_user_Button.setText(_translate("MainWindow", "Add User"))
        self.lvl_usr_ComboBox.setItemText(0, _translate("MainWindow", "1"))
        self.lvl_usr_ComboBox.setItemText(1, _translate("MainWindow", "2"))
        self.lvl_usr_ComboBox.setItemText(2, _translate("MainWindow", "3"))
        self.lvl_usr_ComboBox.setItemText(3, _translate("MainWindow", "4"))
        self.label_18.setText(_translate("MainWindow", "Level of Access"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Client-Management"))
        self.logLabel.setText(_translate("MainWindow", "Log"))
        self.actionClose.setText(_translate("MainWindow", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
