# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ClientUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(448, 485)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(448, 485))
        MainWindow.setMaximumSize(QtCore.QSize(448, 485))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 90, 421, 161))
        self.tabWidget.setObjectName("tabWidget")
        self.acamTab = QtWidgets.QWidget()
        self.acamTab.setAccessibleName("")
        self.acamTab.setAutoFillBackground(False)
        self.acamTab.setObjectName("acamTab")
        self.addc_Button = QtWidgets.QPushButton(self.acamTab)
        self.addc_Button.setGeometry(QtCore.QRect(220, 60, 181, 31))
        self.addc_Button.setObjectName("addc_Button")
        self.label_5 = QtWidgets.QLabel(self.acamTab)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 91, 21))
        self.label_5.setObjectName("label_5")
        self.CamNameComboBox = QtWidgets.QComboBox(self.acamTab)
        self.CamNameComboBox.setGeometry(QtCore.QRect(110, 21, 261, 21))
        self.CamNameComboBox.setObjectName("CamNameComboBox")
        self.tabWidget.addTab(self.acamTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.CamNameComboBox_2 = QtWidgets.QComboBox(self.tab)
        self.CamNameComboBox_2.setGeometry(QtCore.QRect(110, 21, 261, 21))
        self.CamNameComboBox_2.setObjectName("CamNameComboBox_2")
        self.addc_Button_2 = QtWidgets.QPushButton(self.tab)
        self.addc_Button_2.setGeometry(QtCore.QRect(220, 60, 181, 31))
        self.addc_Button_2.setObjectName("addc_Button_2")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 91, 21))
        self.label_7.setObjectName("label_7")
        self.tabWidget.addTab(self.tab, "")
        self.LogtextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.LogtextBrowser.setGeometry(QtCore.QRect(10, 270, 421, 161))
        self.LogtextBrowser.setObjectName("LogtextBrowser")
        self.logLabel = QtWidgets.QLabel(self.centralwidget)
        self.logLabel.setGeometry(QtCore.QRect(20, 250, 51, 21))
        self.logLabel.setObjectName("logLabel")
        self.Refresh_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Refresh_Button.setGeometry(QtCore.QRect(240, 40, 181, 31))
        self.Refresh_Button.setObjectName("Refresh_Button")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 20, 41, 21))
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 50, 91, 21))
        self.label_8.setObjectName("label_8")
        self.user_label = QtWidgets.QLabel(self.centralwidget)
        self.user_label.setGeometry(QtCore.QRect(70, 20, 91, 21))
        self.user_label.setObjectName("user_label")
        self.lvl_label = QtWidgets.QLabel(self.centralwidget)
        self.lvl_label.setGeometry(QtCore.QRect(120, 50, 91, 21))
        self.lvl_label.setObjectName("lvl_label")
        self.LogtextBrowser.raise_()
        self.logLabel.raise_()
        self.tabWidget.raise_()
        self.Refresh_Button.raise_()
        self.label_6.raise_()
        self.label_8.raise_()
        self.user_label.raise_()
        self.lvl_label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 448, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.acamTab.setToolTip(_translate("MainWindow", "<html><head/><body><p>Add Camera</p></body></html>"))
        self.addc_Button.setText(_translate("MainWindow", "Show Camera"))
        self.label_5.setText(_translate("MainWindow", "Camera Selection"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.acamTab), _translate("MainWindow", "Stream Tab"))
        self.addc_Button_2.setText(_translate("MainWindow", "play back Camera"))
        self.label_7.setText(_translate("MainWindow", "Camera Selection"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Playback Tab"))
        self.logLabel.setText(_translate("MainWindow", "Log"))
        self.Refresh_Button.setText(_translate("MainWindow", "Refresh"))
        self.label_6.setText(_translate("MainWindow", "User:"))
        self.label_8.setText(_translate("MainWindow", "Level of access:"))
        self.user_label.setText(_translate("MainWindow", "None"))
        self.lvl_label.setText(_translate("MainWindow", "3"))
        self.actionClose.setText(_translate("MainWindow", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
