# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ServerUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(448, 485)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(448, 485))
        MainWindow.setMaximumSize(QtCore.QSize(448, 485))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 421, 241))
        self.tabWidget.setObjectName("tabWidget")
        self.acamTab = QtWidgets.QWidget()
        self.acamTab.setAccessibleName("")
        self.acamTab.setAutoFillBackground(False)
        self.acamTab.setObjectName("acamTab")
        self.addc_Button = QtWidgets.QPushButton(self.acamTab)
        self.addc_Button.setGeometry(QtCore.QRect(220, 130, 181, 31))
        self.addc_Button.setObjectName("addc_Button")
        self.label_5 = QtWidgets.QLabel(self.acamTab)
        self.label_5.setGeometry(QtCore.QRect(10, 19, 91, 21))
        self.label_5.setObjectName("label_5")
        self.processor_lyr_lineEdit = QtWidgets.QLineEdit(self.acamTab)
        self.processor_lyr_lineEdit.setGeometry(QtCore.QRect(110, 50, 261, 20))
        self.processor_lyr_lineEdit.setObjectName("processor_lyr_lineEdit")
        self.label_8 = QtWidgets.QLabel(self.acamTab)
        self.label_8.setGeometry(QtCore.QRect(10, 49, 81, 21))
        self.label_8.setObjectName("label_8")
        self.lvl_ComboBox = QtWidgets.QComboBox(self.acamTab)
        self.lvl_ComboBox.setGeometry(QtCore.QRect(110, 80, 261, 21))
        self.lvl_ComboBox.setObjectName("lvl_ComboBox")
        self.lvl_ComboBox.addItem("")
        self.lvl_ComboBox.addItem("")
        self.lvl_ComboBox.addItem("")
        self.lvl_ComboBox.addItem("")
        self.label_17 = QtWidgets.QLabel(self.acamTab)
        self.label_17.setGeometry(QtCore.QRect(10, 80, 81, 21))
        self.label_17.setObjectName("label_17")
        self.CamNameComboBox = QtWidgets.QComboBox(self.acamTab)
        self.CamNameComboBox.setGeometry(QtCore.QRect(110, 20, 261, 21))
        self.CamNameComboBox.setObjectName("CamNameComboBox")
        self.Refresh_Button = QtWidgets.QPushButton(self.acamTab)
        self.Refresh_Button.setGeometry(QtCore.QRect(20, 130, 181, 31))
        self.Refresh_Button.setObjectName("Refresh_Button")
        self.tabWidget.addTab(self.acamTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.StrSenButton = QtWidgets.QPushButton(self.tab)
        self.StrSenButton.setGeometry(QtCore.QRect(90, 90, 111, 31))
        self.StrSenButton.setObjectName("StrSenButton")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 91, 21))
        self.label_3.setObjectName("label_3")
        self.AlgComboBox = QtWidgets.QComboBox(self.tab)
        self.AlgComboBox.setGeometry(QtCore.QRect(120, 30, 231, 21))
        self.AlgComboBox.setObjectName("AlgComboBox")
        self.StpSenButton = QtWidgets.QPushButton(self.tab)
        self.StpSenButton.setGeometry(QtCore.QRect(210, 90, 111, 31))
        self.StpSenButton.setObjectName("StpSenButton")
        self.delete_store_cam_Button = QtWidgets.QPushButton(self.tab)
        self.delete_store_cam_Button.setGeometry(QtCore.QRect(270, 180, 101, 31))
        self.delete_store_cam_Button.setObjectName("delete_store_cam_Button")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 71, 21))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.Kill_processComboBox = QtWidgets.QComboBox(self.tab)
        self.Kill_processComboBox.setGeometry(QtCore.QRect(120, 150, 231, 21))
        self.Kill_processComboBox.setObjectName("Kill_processComboBox")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(100, 130, 281, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setEnabled(False)
        self.label_6.setGeometry(QtCore.QRect(10, 130, 81, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setEnabled(False)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.label_7.setObjectName("label_7")
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(90, 10, 291, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(20, 150, 81, 21))
        self.label_9.setObjectName("label_9")
        self.process_spinBox = QtWidgets.QSpinBox(self.tab)
        self.process_spinBox.setGeometry(QtCore.QRect(130, 60, 61, 22))
        self.process_spinBox.setMaximum(255)
        self.process_spinBox.setProperty("value", 45)
        self.process_spinBox.setObjectName("process_spinBox")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(20, 60, 91, 21))
        self.label_10.setObjectName("label_10")
        self.StpSenButton_2 = QtWidgets.QPushButton(self.tab)
        self.StpSenButton_2.setGeometry(QtCore.QRect(220, 60, 91, 21))
        self.StpSenButton_2.setObjectName("StpSenButton_2")
        self.tabWidget.addTab(self.tab, "")
        self.LogtextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.LogtextBrowser.setGeometry(QtCore.QRect(10, 270, 421, 161))
        self.LogtextBrowser.setObjectName("LogtextBrowser")
        self.logLabel = QtWidgets.QLabel(self.centralwidget)
        self.logLabel.setGeometry(QtCore.QRect(20, 250, 51, 21))
        self.logLabel.setObjectName("logLabel")
        self.LogtextBrowser.raise_()
        self.logLabel.raise_()
        self.tabWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 448, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.acamTab.setToolTip(_translate("MainWindow", "<html><head/><body><p>Add Camera</p></body></html>"))
        self.addc_Button.setText(_translate("MainWindow", "Add camera"))
        self.label_5.setText(_translate("MainWindow", "Camera Selection"))
        self.processor_lyr_lineEdit.setText(_translate("MainWindow", "pc1"))
        self.label_8.setText(_translate("MainWindow", "Processor Name"))
        self.lvl_ComboBox.setItemText(0, _translate("MainWindow", "1"))
        self.lvl_ComboBox.setItemText(1, _translate("MainWindow", "2"))
        self.lvl_ComboBox.setItemText(2, _translate("MainWindow", "3"))
        self.lvl_ComboBox.setItemText(3, _translate("MainWindow", "4"))
        self.label_17.setText(_translate("MainWindow", "Level of Access"))
        self.Refresh_Button.setText(_translate("MainWindow", "Refresh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.acamTab), _translate("MainWindow", "Add Processing Layer"))
        self.StrSenButton.setStatusTip(_translate("MainWindow", "it will activate the camera to send data to clients and store it for future access."))
        self.StrSenButton.setText(_translate("MainWindow", "Activate Algorithm"))
        self.label_3.setText(_translate("MainWindow", "Algorithm Selection"))
        self.StpSenButton.setStatusTip(_translate("MainWindow", "it will deactivate the camera but still exist and could be activated again."))
        self.StpSenButton.setText(_translate("MainWindow", "Deactivate Algorithm"))
        self.delete_store_cam_Button.setStatusTip(_translate("MainWindow", "it will remove the data stored inside the server."))
        self.delete_store_cam_Button.setText(_translate("MainWindow", "delete stored data"))
        self.label_6.setText(_translate("MainWindow", "Storage control"))
        self.label_7.setText(_translate("MainWindow", "Process control"))
        self.label_9.setText(_translate("MainWindow", "Processor Name"))
        self.label_10.setText(_translate("MainWindow", "frame Hop"))
        self.StpSenButton_2.setStatusTip(_translate("MainWindow", "it will deactivate the camera but still exist and could be activated again."))
        self.StpSenButton_2.setText(_translate("MainWindow", "update"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Process Controller"))
        self.logLabel.setText(_translate("MainWindow", "Log"))
        self.actionClose.setText(_translate("MainWindow", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
